### ISSUE TITLE
Image not rendering in local dev

### ISSUE THREAD

**Issue by YamatoDX** [skn437/skn-next-tailwind#1]

**Comment by YamatoDX** [comment]
![image](https://user-images.githubusercontent.com/78369801/189526504-673fea07-4ec4-44fd-bb9b-134612950493.png)

**Comment by YamatoDX** [comment]
![image](https://user-images.githubusercontent.com/78369801/189526584-e7b098db-c485-4006-8c0d-ac6a960d00ce.png)

**Comment by YamatoDX** [comment]
@skn437  Follow the screenshots!

**Comment by skn437** [comment]
problem solved....
